# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: "monthly"
  versioning-strategy: increase
  ignore:
    - dependency-name: "*" #All the dependency it's going to ignore for major update
      update-types: [ "version-update:semver-major" ]
